name: Deploy to Heroku

on:
  push:
    branches: ["master"]
  workflow_dispatch:

concurrency:
  group: heroku-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Auth Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          {
            printf 'machine api.heroku.com\n  login %s\n  password %s\n' "$HEROKU_EMAIL" "$HEROKU_API_KEY"
            printf 'machine git.heroku.com\n  login %s\n  password %s\n' "$HEROKU_EMAIL" "$HEROKU_API_KEY"
          } > ~/.netrc
          chmod 600 ~/.netrc
          heroku whoami

      - name: Push to Heroku (force)
        env:
          HEROKU_APP_NAME: vinyls-backend
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master -f
